workflows:
  flutter-build-android:
    name: Flutter Build Android (APK & AAB)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      vars:
        WEB_URL: "https://flutter.dev"
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --dart-define=WEB_URL=$WEB_URL

    artifacts:
      - build/**/outputs/apk/**/*.apk

    publishing:
      email:
        recipients:
          - "thamaraikannan137@gmail.com"
