definitions:
  mac_mini_m1: &mac_mini_m1
    instance_type: mac_mini_m1
    max_build_duration: 30

  environment:
    app_details:
      vars:
        APP_NAME: $APP_NAME
        ORG_NAME: $ORG_NAME
        SPLASH: $SPLASH
        LOGO_URL: $LOGO_URL
        WEBSITE_URL: $WEBSITE_URL

  artifacts:
    #- &ipa_file build/ios/ipa/*.ipa
    #- &xcode_log /tmp/xcodebuild_logs/*.log
    #- &dsym $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    # - &app $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    - &android_abb build/**/outputs/**/*.aab
    - &android_apk build/**/outputs/**/*.apk
    #- &android_mapping_txt build/**/outputs/**/mapping.txt
    #3- &flutter_drive_log flutter_drive.log

  email_release: &email_release
    email:
      recipients:
        - thamaraikannan137@gmail.com
      notify:
        success: true
        failure: true

  scripts:
    - &pub_get
      name: Get packages
      script: |
        flutter packages pub get
        flutter pub get

    - &change_bundle_name
      name: Change bundle name
      script: |
        flutter pub run rename --bundleId "$ORG_NAME.$APP_NAME"
        flutter pub get

    - &change_app_name
      name: Change app name
      script: |
        flutter pub run rename --appname $appName
        flutter pub get

    - &build_abb
      name: Build ABB
      script: |
        flutter build appbundle --release --dart-define="URL=$url"

    - &build_apk
      name: Build APK
      script: |
        flutter build apk --release --dart-define="URL=$url"
    

workflows:
    android-workflow:
      name: Android Workflow
      max_build_duration: 30
      <<: *mac_mini_m1
      scripts:
        - *pub_get
        - *change_bundle_name
        - *change_app_name
        - *build_abb
        - *build_apk
      artifacts:
        - *android_apk
        - *android_abb
      publishing: *email_release
