workflows:
  flutter-build-apk:
    name: Flutter Build APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      vars:
        WEB_URL: "https://flutter.dev"  # Default URL, will be replaced later
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --dart-define=WEB_URL=$WEB_URL
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - "thamaraikannan137@gmail.com"
