name: web_to_apk
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rename: ^3.0.2
  flutter_launcher_icons: ^0.14.3
  flutter_inappwebview: ^6.0.0
  firebase_messaging: ^15.2.2
  firebase_core: ^3.11.0
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android_gravity: fill
  ios_content_mode: scaleAspectFit
  fullscreen: true
  branding: assets/images/splash.png
  branding_mode: bottom
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
